from django.urls import path

from .views import (
    active_loans_report,
    contribution_delete,
    contribution_edit,
    contribution_create,
    dashboard,
    editor_access,
    editor_lock,
    interest_payout_all_create,
    installment_delete,
    installment_edit,
    installment_payment_create,
    interest_payout_report,
    loan_delete,
    loan_disbursement_report,
    loan_edit,
    loan_create,
    member_detail,
    member_edit,
    member_create,
    member_remove,
    member_report,
    monthly_summary_report,
    overdue_report,
    payment_create,
    skip_next_savings_installments,
)


urlpatterns = [
    path("", dashboard, name="dashboard"),
    path("editor-access/", editor_access, name="editor-access"),
    path("editor-lock/", editor_lock, name="editor-lock"),
    path("members/new/", member_create, name="member-create"),
    path("members/<int:member_id>/edit/", member_edit, name="member-edit"),
    path("payments/new/", payment_create, name="payment-create"),
    path("contributions/new/", contribution_create, name="contribution-create"),
    path("contributions/<int:contribution_id>/edit/", contribution_edit, name="contribution-edit"),
    path("contributions/<int:contribution_id>/delete/", contribution_delete, name="contribution-delete"),
    path("installments/new/", installment_payment_create, name="installment-payment-create"),
    path("installments/<int:installment_id>/edit/", installment_edit, name="installment-edit"),
    path("installments/<int:installment_id>/delete/", installment_delete, name="installment-delete"),
    path("loans/new/", loan_create, name="loan-create"),
    path("loans/<int:loan_id>/edit/", loan_edit, name="loan-edit"),
    path("loans/<int:loan_id>/delete/", loan_delete, name="loan-delete"),
    path("reports/active-loans/", active_loans_report, name="active-loans-report"),
    path("reports/cash-given-out/", loan_disbursement_report, name="loan-disbursement-report"),
    path("reports/interest-given-out/", interest_payout_report, name="interest-payout-report"),
    path("interest-payouts/new/", interest_payout_all_create, name="interest-payout-all-create"),
    path("members/<int:member_id>/", member_detail, name="member-detail"),
    path("members/<int:member_id>/remove/", member_remove, name="member-remove"),
    path("savings/skip-next/", skip_next_savings_installments, name="skip-next-savings-installments"),
    path("reports/members/", member_report, name="member-report"),
    path("reports/monthly-summary/", monthly_summary_report, name="monthly-summary-report"),
    path("reports/overdue/", overdue_report, name="overdue-report"),
]
